# Generated by Django 3.0 on 2021-08-03 20:18

from django.db import migrations, models
import website.models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20210803_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='docfile',
            field=models.FileField(upload_to=website.models.Document.generate_path),
        ),
    ]
